export interface IFormDatosPersonal{
  primerNombre: string,
  segundoNombre: string,
  apPaterno: string,
  apMaterno: string,
  dni: string,
  genero: string,
  fechaNacimiento: Date,
  pais: string,
  ciudad: { id: number, nombre: string },
  direccion: string,
  formacion: { id: number, nombre: string },
  empresa: { id: number, nombre: string },
  industria: { id: number, nombre: string },
  trabajo: { id: number, nombre: string },
  cargo: { id: number, nombre: string },
  nombreFamiliar: string,
  parentesco: string,
  telefonoFamiliar: string,
  emailPrincipal: string,
  emailSecundario: string,
  emailPrincipalAux: string,
  emailSecundarioAux: string,
  celularPrincipal: string,
  celularSecundario: string,
  celularPrincipalAux: string,
  celularSecundarioAux: string,
  telefonoPrincipal: string,
  telefonoSecundario: string,
  telefonoPrincipalAux: string,
  telefonoSecundarioAux: string,
}
