export interface Personal {
}

export interface DatosPersonal {
  datosPersonal: {
    id: number,
    nombres: string,
    apellidos: string,
    rol: string,
    tipoPersonal: string,
    email: string,
    areaAbrev: string,
    anexo: string,
    idJefe: number,
    central: string,
    activo: boolean,
    apellidoPaterno: string,
    apellidoMaterno: string,
    idSexo: number,
    idEstadocivil: number,
    fechaNacimiento: Date,
    idPaisNacimiento: number,
    idRegion: number,
    idCiudad: number,
    idTipoDocumento: number,
    numeroDocumento: string,
    autogeneradoEssalud: string,
    idTipoSangre: number,
    urlFirmaCorreos: string,
    idGrupoProgramasCriticos: number,
    idCerrador: number,
    esCerrador: boolean,
    idPaisDireccion: number,
    idRegionDireccion: number,
    ciudadDireccion: string,
    nombreDireccion: string,
    fijoReferencia: string,
    movilReferencia: string,
    emailReferencia: string,
    idSistemaPensionario: number,
    idEntidadSistemaPensionario: number,
    nombreCuspp: string,
    distritoDireccion: string,
    conEssalud: boolean,
    idBusqueda: number,
    aliasEmailAsesor: string,
    anexo3Cx: string,
    id3Cx: string,
    password3Cx: string,
    dominio: string,
    idFacebookPersonal: number,
    estado: boolean,
    usuarioCreacion: string,
    usuarioModificacion: string,
    fechaCreacion: Date,
    fechaModificacion: Date,
    esPersonaValida: boolean,
    urlFoto: string,
    aplicaFirmaHtml: boolean,
    firmaHtml: string,
    cargoFirmaHtml: string,
    idPostulante: number,
    usuarioAsterisk: number,
    contrasenaAsterisk: string,
    idTableroComercialCategoriaAsesor: number,
    idPuestoTrabajoNivel: number,
    idPersonalAreaTrabajo: number,
    idPersonalArchivo: number,
    idRolUsuarioTicket: number,
    discadorActivo: boolean,
    diferenciaHoraria: number
  },

  asignados: {
    id: number,
    nombres: string,
    email: string,
    activo: boolean,
    usuario: string,
    tipoPersonal: string,
    nivelVisualizacionAgenda: string
  }[];
}
