export interface Subestado{
 Id : number,
 Nombre : string, 
 IdEstadoMatricula:number
}

export interface EstadoPago{
    Id : number,
 Nombre : string, 
}


export interface EnvioFiltroSegmen{
        Id : number,
        IdFiltroSegmentoTipoContacto : number,
        Nombre : string, 
        Descripcion : string, 
        IdOperadorComparacionNroSolicitudInformacion : number,
        NroSolicitudInformacion : number,
        IdOperadorComparacionNroOportunidades : number,
        NroOportunidades : number,

         FechaInicioCreacionUltimaOportunidad : string, 
         FechaFinCreacionUltimaOportunidad : string, 
         FechaInicioModificacionUltimaActividadDetalle : string, 
         FechaFinModificacionUltimaActividadDetalle : string, 

        EsRn2 :boolean,
         FechaInicioProgramacionUltimaActividadDetalleRn2 : string, 
         FechaFinProgramacionUltimaActividadDetalleRn2 : string, 

        //Fecha formulario
         FechaInicioFormulario : string, 
         FechaFinFormulario : string, 
        //Fecha chat
         FechaInicioChatIntegra : string, 
         FechaFinChatIntegra : string, 
        IdOperadorComparacionTiempoMaximoRespuestaChatOnline : number,
        TiempoMaximoRespuestaChatOnline : number,
        IdOperadorComparacionNroPalabrasClienteChatOnline : number,
        NroPalabrasClienteChatOnline : number,
        IdOperadorComparacionTiempoPromedioRespuestaChatOnline : number,
        TiempoPromedioRespuestaChatOnline : number,
        IdOperadorComparacionNroPalabrasClienteChatOffline : number,
        NroPalabrasClienteChatOffline : number,
        //correo
         FechaInicioCorreo : string, 
         FechaFinCorreo : string, 
        IdOperadorComparacionNroCorreosAbiertos : number,
        NroCorreosAbiertos : number,
        IdOperadorComparacionNroCorreosNoAbiertos : number,
        NroCorreosNoAbiertos : number,
        IdOperadorComparacionNroClicksEnlace : number,
        NroClicksEnlace : number,
        EsSuscribirme :boolean,
        EsDesuscribirme :boolean,

        IdOperadorComparacionNroCorreosAbiertosMailChimp : number,
        NroCorreosAbiertosMailChimp : number,
        IdOperadorComparacionNroCorreosNoAbiertosMailChimp : number,
        NroCorreosNoAbiertosMailChimp : number,
        IdOperadorComparacionNroClicksEnlaceMailChimp : number,
        NroClicksEnlaceMailChimp : number,

        ConsiderarFiltroGeneral :boolean,
        ConsiderarFiltroEspecifico :boolean,
        TieneVentaCruzada :boolean,
        IdOperadorComparacionNroTotalLineaCreditoVigente : number,
        NroTotalLineaCreditoVigente : number,
        IdOperadorComparacionMontoTotalLineaCreditoVigente : number,
        MontoTotalLineaCreditoVigente : number,
        IdOperadorComparacionMontoMaximoOtorgadoLineaCreditoVigente : number,
        MontoMaximoOtorgadoLineaCreditoVigente : number,
        IdOperadorComparacionMontoMinimoOtorgadoLineaCreditoVigente : number,
        MontoMinimoOtorgadoLineaCreditoVigente : number,
        IdOperadorComparacionNroTotalLineaCreditoVigenteVencida : number,
        NroTotalLineaCreditoVigenteVencida : number,
        IdOperadorComparacionMontoTotalLineaCreditoVigenteVencida : number,
        MontoTotalLineaCreditoVigenteVencida : number,
        IdOperadorComparacionNroTcOtorgada : number,
        NroTcOtorgada : number,
        IdOperadorComparacionMontoTotalOtorgadoEnTcs : number,
        MontoTotalOtorgadoEnTcs : number,
        IdOperadorComparacionMontoMaximoOtorgadoEnUnaTc : number,
        MontoMaximoOtorgadoEnUnaTc : number,
        IdOperadorComparacionMontoMinimoOtorgadoEnUnaTc : number,
        MontoMinimoOtorgadoEnUnaTc : number,
        IdOperadorComparacionMontoDisponibleTotalEnTcs : number,
        MontoDisponibleTotalEnTcs : number,
         FechaInicioLlamada : string, 
         FechaFinLlamada : string, 
        IdOperadorComparacionDuracionPromedioLlamadaPorOportunidad : number,
        DuracionPromedioLlamadaPorOportunidad : number,
        IdOperadorComparacionDuracionTotalLlamadaPorOportunidad : number,
        DuracionTotalLlamadaPorOportunidad : number,
        IdOperadorComparacionNroLlamada : number,
        NroLlamada : number,
        IdOperadorComparacionDuracionLlamada : number,
        DuracionLlamada : number,
        IdOperadorComparacionTasaEjecucionLlamada : number,
        TasaEjecucionLlamada : number,

        //Tab interaccion sitio web
        FechaInicioInteraccionSitioWeb : string, 
        FechaFinInteraccionSitioWeb : string, 
        IdOperadorComparacionTiempoVisualizacionTotalSitioWeb : number,
        TiempoVisualizacionTotalSitioWeb : number,
        IdOperadorComparacionNroClickEnlaceTodoSitioWeb : number,
        NroClickEnlaceTodoSitioWeb : number,
        IdOperadorComparacionTiempoVisualizacionTotalPaginaPrograma : number,
        TiempoVisualizacionTotalPaginaPrograma : number,
        IdOperadorComparacionTiempoVisualizacionMaximaEnUnaPaginaWebPaginaProgramas : number,
        TiempoVisualizacionMaximaEnUnaPaginaWebPaginaProgramas : number,
        IdOperadorComparacionNroClickEnlacePaginaPrograma : number,
        NroClickEnlacePaginaPrograma : number,
        ConsiderarVisualizacionVideoVistaPreviaPaginaPrograma :boolean,
        ConsiderarClickBotonMatricularmePaginaPrograma : boolean,
        ConsiderarClickBotonVersionPruebaPaginaPrograma :boolean,
        IdOperadorComparacionTiempoVisualizacionTotalPaginaBscampus : number,
        TiempoVisualizacionTotalPaginaBscampus : number,
        IdOperadorComparacionTiempoVisualizacionMaximaEnUnaPaginaWebPaginaBscampus : number,
        TiempoVisualizacionMaximaEnUnaPaginaWebPaginaBscampus : number,
        IdOperadorComparacionNroVisitasDirectorioTagAreaSubArea : number,
        NroVisitasDirectorioTagAreaSubArea : number,
        IdOperadorComparacionTiempoVisualizacionTotalDirectorioTagAreaSubArea : number,
        TiempoVisualizacionTotalDirectorioTagAreaSubArea : number,
        IdOperadorComparacionNroClickEnlaceDirectorioTagAreaSubArea : number,
        NroClickEnlaceDirectorioTagAreaSubArea : number,
        IdOperadorComparacionNroVisitasPaginaMisCursos : number,
        NroVisitasPaginaMisCursos : number,
        IdOperadorComparacionTiempoVisualizacionTotalPaginaMisCursos : number,
        TiempoVisualizacionTotalPaginaMisCursos : number,
        IdOperadorComparacionNroClickEnlacePaginaMisCursos : number,
        NroClickEnlacePaginaMisCursos : number,
        IdOperadorComparacionNroVisitaPaginaCursoDiplomado : number,
        NroVisitaPaginaCursoDiplomado : number,
        IdOperadorComparacionTiempoVisualizacionTotalPaginaCursoDiplomado : number,
        TiempoVisualizacionTotalPaginaCursoDiplomado : number,
        IdOperadorComparacionNroClicksEnlacePaginaCursoDiplomado : number,
        NroClicksEnlacePaginaCursoDiplomado : number,
        ConsiderarClickFiltroPaginaCursoDiplomado :boolean,

        IdOperadorComparacionNroSolicitudInformacionPg : number,
        NroSolicitudInformacionPg : number,
        IdOperadorComparacionNroSolicitudInformacionArea : number,
        NroSolicitudInformacionArea : number,
        IdOperadorComparacionNroSolicitudInformacionSubArea : number,
        NroSolicitudInformacionSubArea : number,

        IdCampaniaGeneral : number,
        TipoAsociacion : number,
        CantidadPeriodoSinRecibirCorreo : number,
        TipoPeriodoSinRecibirCorreo : number,
        IdProbabilidadOportunidad : number,
        NumeroSegmento : number,
        IdPrioridadMailChimpLista : number,
        IdCategoriaObjetoFiltro : number,

       ConsiderarOportunidadHistorica :boolean,
       ConsiderarCategoriaDato :boolean,
       ConsiderarInteraccionOfflineOnline :boolean,
       ConsiderarInteraccionSitioWeb :boolean,
       ConsiderarInteraccionFormularios :boolean,
       ConsiderarInteraccionChatPw :boolean,
       ConsiderarInteraccionCorreo :boolean,
       ConsiderarHistorialFinanciero :boolean,
       ConsiderarInteraccionWhatsApp :boolean,
       ConsiderarInteraccionChatMessenger :boolean,
       ConsiderarEnvioAutomatico :boolean,
       ExcluirPorCorreoEnviadoMismoProgramaGeneralPrincipal :boolean,
         FechaInicioExcluirPorCorreoEnviadoMismoProgramaGeneralPrincipal : string, 
         FechaFinExcluirPorCorreoEnviadoMismoProgramaGeneralPrincipal : string, 

        IdTiempoFrecuenciaMatriculaAlumno : number,
        CantidadTiempoMatriculaAlumno : number,

        ConsiderarConMessengerValido :boolean,
        ConsiderarConWhatsAppValido :boolean,
        ConsiderarConEmailValido :boolean,

        IdTiempoFrecuenciaCumpleaniosContactoDentroDe : number,
        CantidadTiempoCumpleaniosContactoDentroDe : number,

         FechaInicioMatriculaAlumno : string, 
         FechaFinMatriculaAlumno : string, 
        ConsiderarAlumnosAsignacionAutomaticaOperaciones :boolean,
        ExcluirMatriculados :boolean,
   
       AplicaSobreCreacionOportunidad :boolean,
        IdOperadorMedidaTiempoCreacionOportunidad : number,
        NroMedidaTiempoCreacionOportunidad : number,
       AplicaSobreUltimaActividad :boolean,
        IdOperadorMedidaTiempoUltimaActividadEjecutada : number,
        NroMedidaTiempoUltimaActividadEjecutada : number,
        EnvioAutomaticoEstadoActividadDetalle :number,
       ConsiderarYaEnviados :boolean,

       
        ListaArea : Array <any>,
        ListaSubArea : Array <any>,
        ListaProgramaGeneral : Array <any>,
        ListaProgramaEspecifico : Array <any>,
        ListaOportunidadInicialFaseMaxima : Array <any>,
        ListaOportunidadInicialFaseActual : Array <any>,
        ListaOportunidadActualFaseMaxima : Array <any>,
        ListaOportunidadActualFaseActual : Array <any>,
        ListaPais : Array <any>,
        ListaCiudad : Array <any>,
        ListaTipoCategoriaOrigen : Array <any>,
        ListaCategoriaOrigen : Array <any>,
        ListaCargo : Array <any>,
        ListaIndustria : Array <any>,
        ListaAreaFormacion : Array <any>,
        ListaAreaTrabajo : Array <any>,


        ListaTipoFormulario : Array <any>,
        ListaTipoInteraccionFormulario : Array <any>,
        ListaProbabilidadOportunidad : Array <any>,
        ListaActividadLlamada : Array <any>,

        ListaVCArea : Array <any>,
        ListaVCSubArea : Array <any>,
        ListaVCPGeneral : Array <any>,

        ListaProbabilidadVentaCruzada : Array <any>,
        ListaProgramaGeneralPrincipalExcluirPorMismoCorreoEnviado : Array <any>,
        ListaExcluirPorFiltroSegmento : Array <any>,
        ListaExcluirPorConjuntoLista : Array <any>,
        ListaExcluirPorCampaniaMailing : Array <any>,

        ListaActividadCabecera : Array <any>,
        ListaOcurrencia : Array <any>,
        ListaDocumentoAlumno : Array <any>,
        ListaEstadoMatricula : Array <any>,
        ListaSubEstadoMatricula : Array <any>,
        ListaModalidadCurso : Array <any>,

         ListaSesion : Array <any>,
         ListaEstadoAcademico : Array <any>,
         ListaEstadoPago : Array <any>,
         ListaPorcentajeAvance : Array <any>,

         ListaEstadoLlamada : Array <any>,

         ListaSesionWebinar : Array <any>,
         ListaTrabajoAlumno : Array <any>,
         ListaTrabajoAlumnoFinal : Array <any>,
        ListaTarifario : Array <any>,

        ListaEnvioAutomaticoOportunidadFaseActual : Array <any>,

        NombreUsuario :string,
        IdCampaniaMailing : number,
        IdCampaniaMailingLista : number,

        IdConjuntoListaDetalle : number,
        NroListasRepeticionContacto : number,
        NroEjecucion : number,
        

}
