export interface GenerarFur{
    id: number,
    codigo: string,
    idCentroCosto: number,
    centroCosto: string,
    programa: string,
    idCiudad: number,
    idFurTipoPedido: number,
    numeroSemana: number,
    idProveedor: number,
    razonSocial:string,
    idProducto: number,
    producto: string,
    idProductoPresentacion: number,
    productoPresentacion: string,
    idMoneda_Proveedor: number,
    fechaLimite: string|Date,
    descripcion: string,
    numeroCuenta: string,
    cuenta: string,
    cantidad: number,
    idFaseAprobacion1: number,
    faseAprobacion1: string,
    precioUnitarioMonedaOrigen:number,
    precioUnitarioDolares: number,
    precioTotalMonedaOrigen: number,
    precioTotalDolares: number,
    usuarioCreacion: string,
    usuarioModificacion: string,
    fechaModificacion: string|Date,
    observaciones: string,
    idMonedaPagoReal: number,
    idPersonalAreaTrabajo:number,
    idCondicionTipoPago: number,
    monedaPagoReal: string,
    idEmpresa: number,
    editarDisable?:boolean|null
}

export interface ParametrosFur{
    idArea: number,
    codigo: string,
    idRol: number,
    idPersonal: number,
    idEstadoFaseAprobacion1: number,
    usuario: string,
    idCiudad: number,
    anio: number,
    semana: number
}

